FROM public.ecr.aws/lambda/python:3.12

# Copy requirements.txt and install packages
COPY requirements.txt ./
RUN pip install -r requirements.txt -t .

# Copy the rest of the application code
COPY app.py ./

# Set the Lambda handler
CMD ["app.lambda_handler"]